app: 
  fullName: user-be-stag
  name: user
  type: be
  env: stag


container:
  port: 8080
  image:
    registry: 067347400935.dkr.ecr.ap-northeast-2.amazonaws.com
    version: 8de003dd32c14a7298bddf735ba5b436f5a53c04

ingress:
  host: stag-api.xquare.app
  prefix: /users
  