app: 
  fullName: point-be-stag
  name: point
  type: be
  env: stag


container:
  port: 8080
  image:
    registry: 067347400935.dkr.ecr.ap-northeast-2.amazonaws.com
    version: 10414fbb1f845dbee473bca9ee74c048a7ee9351

ingress:
  host: stag-api.xquare.app
  prefix: /points
