app: 
  fullName: point-be-stag
  name: point
  type: be
  env: stag


container:
  port: 8080
  image:
    registry: 067347400935.dkr.ecr.ap-northeast-2.amazonaws.com
    version: 41c19a518a2e62d8423ca53212c69711317dfd31

ingress:
  host: stag-api.xquare.app
  prefix: /points
