app:
  fullName: feed-be-stag
  name: feed
  type: be
  env: stag

container:
  port: 8080
  image:
    registry: 067347400935.dkr.ecr.ap-northeast-2.amazonaws.com
    version: 0448e8207d5f0663b61ffc61a7b351546a4280c6

ingress:
  host: stag-api.xquare.app
  prefix: /feeds
